### ISSUE TITLE
Issue installing langcog with new version of R

### ISSUE THREAD

**Issue by erbschille** [langcog/langcog#12]
Hello! I've been using the langcog package, specifically the multi_boot_standard() function. All has been going swimmingly until (!) I just updated to the new version of R (4.4.1 "Race for Your Life"). Now when I try to install langcog using the command

`devtools::install_github("langcog/langcog")`

I get the following error:

```
Using GitHub PAT from the git credential store.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2024-10-10 20:58:37 UTC
```

I actually solved a similar issue with *another* package by updating R...so this error is a bit mysterious to me. Do you have any suggestions? 

Thank you!

**Comment by mcfrank** [comment]
I reproduced your error and fixed it by following the instructions here:
https://stackoverflow.com/questions/70908295/failed-to-install-unknown-package-from-github

it has to do with your personal access token for github being set wrong in
R. :)

**Comment by erbschille** [comment]
Thank you! I did indeed have an expired PAT!
