### ISSUE TITLE
`multi_boot()` performance issues; `summarise_all()` is deprecated

### ISSUE THREAD

**Issue by kgweisman** [langcog/langcog#6]
I just updated R (version 3.4.1), RStudio (version 1.0.153), and all my packages, and I'm using `tidyverse`. Running a `multi_boot()` that worked quickly (within ~30 seconds) last week (`mean_na()` etc. are functions that I've defined above):

```
char_plotting_ratings_s1 <- d1 %>% 
  select(subid, character, capacity, responseNum) %>%
  multi_boot(column = "responseNum",
             summary_function = "mean_na",
             summary_groups = c("character", "capacity"),
             statistics_functions = c("ci_lower_na", "mean_na", "ci_upper_na")) %>%
  full_join(demoSampleSize("study 1") %>% filter(character != "all")) %>%
  mutate(study = "study 1")
```

This now takes >5 minutes, and produces the following warning message:

```
`summarise_each()` is deprecated.
Use `summarise_all()`, `summarise_at()` or `summarise_if()` instead.
To map `funs` over a selection of variables, use `summarise_at()`
```

Just thought I'd let you guys know, since I love this package and especially `multi_boot()`!

**Comment by mhtess** [comment]
I've run into the same problem when installing `langcog/langcog` in a fresh packrat session

**Comment by mcfrank** [comment]
hi guys, I think @mikabr and @dyurovsky are trying to work something out to fix this... it got complicated unfortunately...
